image: node
clone:
  depth: full
pipelines:
  master:
    - step:
        script:
          - npm install
          #- npm test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master